// ReSharper disable MemberCanBePrivate.Global
namespace Peereflits.Shared.Types.Mimes;

public class MimeType
{
    private MimeType(string extension, string mime)
    {
        Extension = extension;
        Mime = mime;
    }

    public string Extension { get; }
    public string Mime { get; }
    public override string ToString() => Mime;

    public static MimeType GetBy(string extension)
    {
        switch(extension?.Trim().ToLowerInvariant())
        {
            case ".323": return Text323;
            case ".3g2": return Video3G2;
            case ".3gp2": return Video3Gp2;
            case ".3gp": return Video3Gp;
            case ".3gpp": return Video3Gpp;
            case ".aac": return AudioAac;
            case ".aaf": return ApplicationAaf;
            case ".aca": return ApplicationAca;
            case ".accdb": return ApplicationAccdb;
            case ".accde": return ApplicationAccde;
            case ".accdt": return ApplicationAccdt;
            case ".acx": return ApplicationAcx;
            case ".adt": return AudioAdt;
            case ".adts": return AudioAdts;
            case ".afm": return ApplicationAfm;
            case ".ai": return ApplicationAi;
            case ".aif": return AudioAif;
            case ".aifc": return AudioAifc;
            case ".aiff": return AudioAiff;
            case ".appcache": return TextAppcache;
            case ".application": return ApplicationApplication;
            case ".art": return ImageArt;
            case ".asd": return ApplicationAsd;
            case ".asf": return VideoAsf;
            case ".asi": return ApplicationAsi;
            case ".asm": return TextAsm;
            case ".asr": return VideoAsr;
            case ".asx": return VideoAsx;
            case ".atom": return ApplicationAtom;
            case ".au": return AudioAu;
            case ".avi": return VideoAvi;
            case ".axs": return ApplicationAxs;
            case ".bas": return TextBas;
            case ".bcpio": return ApplicationBcpio;
            case ".bin": return ApplicationBin;
            case ".bmp": return ImageBmp;
            case ".c": return TextC;
            case ".cab": return ApplicationCab;
            case ".calx": return ApplicationCalx;
            case ".cat": return ApplicationCat;
            case ".cdf": return ApplicationCdf;
            case ".chm": return ApplicationChm;
            case ".class": return ApplicationClass;
            case ".clp": return ApplicationClp;
            case ".cmx": return ImageCmx;
            case ".cnf": return TextCnf;
            case ".cod": return ImageCod;
            case ".cpio": return ApplicationCpio;
            case ".cpp": return TextCpp;
            case ".crd": return ApplicationCrd;
            case ".crl": return ApplicationCrl;
            case ".crt": return ApplicationCrt;
            case ".csh": return ApplicationCsh;
            case ".css": return TextCss;
            case ".csv": return ApplicationCsv;
            case ".cur": return ApplicationCur;
            case ".dcr": return ApplicationDcr;
            case ".deploy": return ApplicationDeploy;
            case ".der": return ApplicationDer;
            case ".dib": return ImageDib;
            case ".dir": return ApplicationDir;
            case ".disco": return TextDisco;
            case ".dll": return ApplicationDll;
            case ".dll.config": return TextDllConfig;
            case ".dlm": return TextDlm;
            case ".doc": return ApplicationDoc;
            case ".docm": return ApplicationDocm;
            case ".docx": return ApplicationDocx;
            case ".dot": return ApplicationDot;
            case ".dotm": return ApplicationDotm;
            case ".dotx": return ApplicationDotx;
            case ".dsp": return ApplicationDsp;
            case ".dtd": return TextDtd;
            case ".dvi": return ApplicationDvi;
            case ".dvr-ms": return VideoDvrMs;
            case ".dwf": return DrawingDwf;
            case ".dwp": return ApplicationDwp;
            case ".dxr": return ApplicationDxr;
            case ".eml": return MessageEml;
            case ".emz": return ApplicationEmz;
            case ".eot": return ApplicationEot;
            case ".eps": return ApplicationEps;
            case ".esd": return ApplicationEsd;
            case ".etx": return TextEtx;
            case ".evy": return ApplicationEvy;
            case ".exe": return ApplicationExe;
            case ".exe.config": return TextExeConfig;
            case ".fdf": return ApplicationFdf;
            case ".fif": return ApplicationFif;
            case ".fla": return ApplicationFla;
            case ".flr": return XWorldFlr;
            case ".flv": return VideoFlv;
            case ".gif": return ImageGif;
            case ".glb": return ModelGlb;
            case ".gtar": return ApplicationGtar;
            case ".gz": return ApplicationGz;
            case ".h": return TextH;
            case ".hdf": return ApplicationHdf;
            case ".hdml": return TextHdml;
            case ".hhc": return ApplicationHhc;
            case ".hhk": return ApplicationHhk;
            case ".hhp": return ApplicationHhp;
            case ".hlp": return ApplicationHlp;
            case ".hqx": return ApplicationHqx;
            case ".hta": return ApplicationHta;
            case ".htc": return TextHtc;
            case ".htm": return TextHtm;
            case ".html": return TextHtml;
            case ".htt": return TextHtt;
            case ".hxt": return TextHxt;
            case ".ico": return ImageIco;
            case ".ics": return TextIcs;
            case ".ief": return ImageIef;
            case ".iii": return ApplicationIii;
            case ".inf": return ApplicationInf;
            case ".ins": return ApplicationIns;
            case ".isp": return ApplicationIsp;
            case ".ivf": return VideoIvf;
            case ".jar": return ApplicationJar;
            case ".java": return ApplicationJava;
            case ".jck": return ApplicationJck;
            case ".jcz": return ApplicationJcz;
            case ".jfif": return ImageJfif;
            case ".jpb": return ApplicationJpb;
            case ".jpe": return ImageJpe;
            case ".jpeg": return ImageJpeg;
            case ".jpg": return ImageJpg;
            case ".js": return ApplicationJs;
            case ".json": return ApplicationJson;
            case ".jsonld": return ApplicationJsonld;
            case ".jsx": return TextJsx;
            case ".latex": return ApplicationLatex;
            case ".less": return TextLess;
            case ".lit": return ApplicationLit;
            case ".lpk": return ApplicationLpk;
            case ".lsf": return VideoLsf;
            case ".lsx": return VideoLsx;
            case ".lzh": return ApplicationLzh;
            case ".m13": return ApplicationM13;
            case ".m14": return ApplicationM14;
            case ".m1v": return VideoM1V;
            case ".m2ts": return VideoM2Ts;
            case ".m3u": return AudioM3U;
            case ".m4a": return AudioM4A;
            case ".m4v": return VideoM4V;
            case ".man": return ApplicationMan;
            case ".manifest": return ApplicationManifest;
            case ".map": return TextMap;
            case ".mdb": return ApplicationMdb;
            case ".mdp": return ApplicationMdp;
            case ".me": return ApplicationMe;
            case ".mht": return MessageMht;
            case ".mhtml": return MessageMhtml;
            case ".mid": return AudioMid;
            case ".midi": return AudioMidi;
            case ".mix": return ApplicationMix;
            case ".mmf": return ApplicationMmf;
            case ".mno": return TextMno;
            case ".mny": return ApplicationMny;
            case ".mov": return VideoMov;
            case ".movie": return VideoMovie;
            case ".mp2": return VideoMp2;
            case ".mp3": return AudioMp3;
            case ".mp4": return VideoMp4;
            case ".mp4v": return VideoMp4V;
            case ".mpa": return VideoMpa;
            case ".mpe": return VideoMpe;
            case ".mpeg": return VideoMpeg;
            case ".mpg": return VideoMpg;
            case ".mpp": return ApplicationMpp;
            case ".mpv2": return VideoMpv2;
            case ".ms": return ApplicationMs;
            case ".msi": return ApplicationMsi;
            case ".mso": return ApplicationMso;
            case ".mvb": return ApplicationMvb;
            case ".mvc": return ApplicationMvc;
            case ".nc": return ApplicationNc;
            case ".nsc": return VideoNsc;
            case ".nws": return MessageNws;
            case ".ocx": return ApplicationOcx;
            case ".oda": return ApplicationOda;
            case ".odc": return TextOdc;
            case ".ods": return ApplicationOds;
            case ".oga": return AudioOga;
            case ".ogg": return VideoOgg;
            case ".ogv": return VideoOgv;
            case ".one": return ApplicationOne;
            case ".onea": return ApplicationOnea;
            case ".onetoc": return ApplicationOnetoc;
            case ".onetoc2": return ApplicationOnetoc2;
            case ".onetmp": return ApplicationOnetmp;
            case ".onepkg": return ApplicationOnepkg;
            case ".osdx": return ApplicationOsdx;
            case ".otf": return FontOtf;
            case ".p10": return ApplicationP10;
            case ".p12": return ApplicationP12;
            case ".p7b": return ApplicationP7B;
            case ".p7c": return ApplicationP7C;
            case ".p7m": return ApplicationP7M;
            case ".p7r": return ApplicationP7R;
            case ".p7s": return ApplicationP7S;
            case ".pbm": return ImagePbm;
            case ".pcx": return ApplicationPcx;
            case ".pcz": return ApplicationPcz;
            case ".pdf": return ApplicationPdf;
            case ".pfb": return ApplicationPfb;
            case ".pfm": return ApplicationPfm;
            case ".pfx": return ApplicationPfx;
            case ".pgm": return ImagePgm;
            case ".pko": return ApplicationPko;
            case ".pma": return ApplicationPma;
            case ".pmc": return ApplicationPmc;
            case ".pml": return ApplicationPml;
            case ".pmr": return ApplicationPmr;
            case ".pmw": return ApplicationPmw;
            case ".png": return ImagePng;
            case ".pnm": return ImagePnm;
            case ".pnz": return ImagePnz;
            case ".pot": return ApplicationPot;
            case ".potm": return ApplicationPotm;
            case ".potx": return ApplicationPotx;
            case ".ppam": return ApplicationPpam;
            case ".ppm": return ImagePpm;
            case ".pps": return ApplicationPps;
            case ".ppsm": return ApplicationPpsm;
            case ".ppsx": return ApplicationPpsx;
            case ".ppt": return ApplicationPpt;
            case ".pptm": return ApplicationPptm;
            case ".pptx": return ApplicationPptx;
            case ".prf": return ApplicationPrf;
            case ".prm": return ApplicationPrm;
            case ".prx": return ApplicationPrx;
            case ".ps": return ApplicationPs;
            case ".psd": return ApplicationPsd;
            case ".psm": return ApplicationPsm;
            case ".psp": return ApplicationPsp;
            case ".pub": return ApplicationPub;
            case ".qt": return VideoQt;
            case ".qtl": return ApplicationQtl;
            case ".qxd": return ApplicationQxd;
            case ".ra": return AudioRa;
            case ".ram": return AudioRam;
            case ".rar": return ApplicationRar;
            case ".ras": return ImageRas;
            case ".rf": return ImageRf;
            case ".rgb": return ImageRgb;
            case ".rm": return ApplicationRm;
            case ".rmi": return AudioRmi;
            case ".roff": return ApplicationRoff;
            case ".rpm": return AudioRpm;
            case ".rtf": return ApplicationRtf;
            case ".rtx": return TextRtx;
            case ".scd": return ApplicationScd;
            case ".sct": return TextSct;
            case ".sea": return ApplicationSea;
            case ".setpay": return ApplicationSetpay;
            case ".setreg": return ApplicationSetreg;
            case ".sgml": return TextSgml;
            case ".sh": return ApplicationSh;
            case ".shar": return ApplicationShar;
            case ".sit": return ApplicationSit;
            case ".sldm": return ApplicationSldm;
            case ".sldx": return ApplicationSldx;
            case ".smd": return AudioSmd;
            case ".smi": return ApplicationSmi;
            case ".smx": return AudioSmx;
            case ".smz": return AudioSmz;
            case ".snd": return AudioSnd;
            case ".snp": return ApplicationSnp;
            case ".spc": return ApplicationSpc;
            case ".spl": return ApplicationSpl;
            case ".spx": return AudioSpx;
            case ".src": return ApplicationSrc;
            case ".ssm": return ApplicationSsm;
            case ".sst": return ApplicationSst;
            case ".stl": return ApplicationStl;
            case ".sv4cpio": return ApplicationSv4Cpio;
            case ".sv4crc": return ApplicationSv4Crc;
            case ".svg": return ImageSvg;
            case ".svgz": return ImageSvgz;
            case ".swf": return ApplicationSwf;
            case ".t": return ApplicationT;
            case ".tar": return ApplicationTar;
            case ".tcl": return ApplicationTcl;
            case ".tex": return ApplicationTex;
            case ".texi": return ApplicationTexi;
            case ".texinfo": return ApplicationTexinfo;
            case ".tgz": return ApplicationTgz;
            case ".thmx": return ApplicationThmx;
            case ".thn": return ApplicationThn;
            case ".tif": return ImageTif;
            case ".tiff": return ImageTiff;
            case ".toc": return ApplicationToc;
            case ".tr": return ApplicationTr;
            case ".trm": return ApplicationTrm;
            case ".ts": return VideoTs;
            case ".tsv": return TextTsv;
            case ".ttf": return ApplicationTtf;
            case ".tts": return VideoTts;
            case ".txt": return TextTxt;
            case ".u32": return ApplicationU32;
            case ".uls": return TextUls;
            case ".ustar": return ApplicationUstar;
            case ".vbs": return TextVbs;
            case ".vcf": return TextVcf;
            case ".vcs": return TextVcs;
            case ".vdx": return ApplicationVdx;
            case ".vml": return TextVml;
            case ".vsd": return ApplicationVsd;
            case ".vss": return ApplicationVss;
            case ".vst": return ApplicationVst;
            case ".vsto": return ApplicationVsto;
            case ".vsw": return ApplicationVsw;
            case ".vsx": return ApplicationVsx;
            case ".vtx": return ApplicationVtx;
            case ".wasm": return ApplicationWasm;
            case ".wav": return AudioWav;
            case ".wax": return AudioWax;
            case ".wbmp": return ImageWbmp;
            case ".wcm": return ApplicationWcm;
            case ".wdb": return ApplicationWdb;
            case ".webm": return VideoWebm;
            case ".wks": return ApplicationWks;
            case ".wm": return VideoWm;
            case ".wma": return AudioWma;
            case ".wmd": return ApplicationWmd;
            case ".wmf": return ApplicationWmf;
            case ".wml": return TextWml;
            case ".wmlc": return ApplicationWmlc;
            case ".wmls": return TextWmls;
            case ".wmlsc": return ApplicationWmlsc;
            case ".wmp": return VideoWmp;
            case ".wmv": return VideoWmv;
            case ".wmx": return VideoWmx;
            case ".wmz": return ApplicationWmz;
            case ".woff": return FontWoff;
            case ".woff2": return ApplicationWoff2;
            case ".wps": return ApplicationWps;
            case ".wri": return ApplicationWri;
            case ".wrl": return XWorldWrl;
            case ".wrz": return XWorldWrz;
            case ".wsdl": return TextWsdl;
            case ".wtv": return VideoWtv;
            case ".wvx": return VideoWvx;
            case ".x": return ApplicationX;
            case ".xaf": return XWorldXaf;
            case ".xaml": return ApplicationXaml;
            case ".xap": return ApplicationXap;
            case ".xbap": return ApplicationXbap;
            case ".xbm": return ImageXbm;
            case ".xdr": return TextXdr;
            case ".xht": return ApplicationXht;
            case ".xhtml": return ApplicationXhtml;
            case ".xla": return ApplicationXla;
            case ".xlam": return ApplicationXlam;
            case ".xlc": return ApplicationXlc;
            case ".xlm": return ApplicationXlm;
            case ".xls": return ApplicationXls;
            case ".xlsb": return ApplicationXlsb;
            case ".xlsm": return ApplicationXlsm;
            case ".xlsx": return ApplicationXlsx;
            case ".xlt": return ApplicationXlt;
            case ".xltm": return ApplicationXltm;
            case ".xltx": return ApplicationXltx;
            case ".xlw": return ApplicationXlw;
            case ".xml": return TextXml;
            case ".xof": return XWorldXof;
            case ".xpm": return ImageXpm;
            case ".xps": return ApplicationXps;
            case ".xsd": return TextXsd;
            case ".xsf": return TextXsf;
            case ".xsl": return TextXsl;
            case ".xslt": return TextXslt;
            case ".xsn": return ApplicationXsn;
            case ".xtp": return ApplicationXtp;
            case ".xwd": return ImageXwd;
            case ".z": return ApplicationZ;
            case ".zip": return ApplicationZip;
            default: return Empty;
        }
    }

    public static readonly MimeType Empty = new MimeType(string.Empty, string.Empty);

    public static readonly MimeType ApplicationAaf = new MimeType(".aaf", "application/octet-stream");
    public static readonly MimeType ApplicationAca = new MimeType(".aca", "application/octet-stream");
    public static readonly MimeType ApplicationAccdb = new MimeType(".accdb", "application/msaccess");
    public static readonly MimeType ApplicationAccde = new MimeType(".accde", "application/msaccess");
    public static readonly MimeType ApplicationAccdt = new MimeType(".accdt", "application/msaccess");
    public static readonly MimeType ApplicationAcx = new MimeType(".acx", "application/internet-property-stream");
    public static readonly MimeType ApplicationAfm = new MimeType(".afm", "application/octet-stream");
    public static readonly MimeType ApplicationAi = new MimeType(".ai", "application/postscript");
    public static readonly MimeType ApplicationApplication = new MimeType(".application", "application/x-ms-application");
    public static readonly MimeType ApplicationAsd = new MimeType(".asd", "application/octet-stream");
    public static readonly MimeType ApplicationAsi = new MimeType(".asi", "application/octet-stream");
    public static readonly MimeType ApplicationAtom = new MimeType(".atom", "application/atom+xml");
    public static readonly MimeType ApplicationAxs = new MimeType(".axs", "application/olescript");
    public static readonly MimeType ApplicationBcpio = new MimeType(".bcpio", "application/x-bcpio");
    public static readonly MimeType ApplicationBin = new MimeType(".bin", "application/octet-stream");
    public static readonly MimeType ApplicationCab = new MimeType(".cab", "application/vnd.ms-cab-compressed");
    public static readonly MimeType ApplicationCalx = new MimeType(".calx", "application/vnd.ms-office.calx");
    public static readonly MimeType ApplicationCat = new MimeType(".cat", "application/vnd.ms-pki.seccat");
    public static readonly MimeType ApplicationCdf = new MimeType(".cdf", "application/x-cdf");
    public static readonly MimeType ApplicationChm = new MimeType(".chm", "application/octet-stream");
    public static readonly MimeType ApplicationClass = new MimeType(".class", "application/x-java-applet");
    public static readonly MimeType ApplicationClp = new MimeType(".clp", "application/x-msclip");
    public static readonly MimeType ApplicationCpio = new MimeType(".cpio", "application/x-cpio");
    public static readonly MimeType ApplicationCrd = new MimeType(".crd", "application/x-mscardfile");
    public static readonly MimeType ApplicationCrl = new MimeType(".crl", "application/pkix-crl");
    public static readonly MimeType ApplicationCrt = new MimeType(".crt", "application/x-x509-ca-cert");
    public static readonly MimeType ApplicationCsh = new MimeType(".csh", "application/x-csh");
    public static readonly MimeType ApplicationCsv = new MimeType(".csv", "application/octet-stream");
    public static readonly MimeType ApplicationCur = new MimeType(".cur", "application/octet-stream");
    public static readonly MimeType ApplicationDcr = new MimeType(".dcr", "application/x-director");
    public static readonly MimeType ApplicationDeploy = new MimeType(".deploy", "application/octet-stream");
    public static readonly MimeType ApplicationDer = new MimeType(".der", "application/x-x509-ca-cert");
    public static readonly MimeType ApplicationDir = new MimeType(".dir", "application/x-director");
    public static readonly MimeType ApplicationDll = new MimeType(".dll", "application/x-msdownload");
    public static readonly MimeType ApplicationDoc = new MimeType(".doc", "application/msword");
    public static readonly MimeType ApplicationDocm = new MimeType(".docm", "application/vnd.ms-word.document.macroEnabled.12");
    public static readonly MimeType ApplicationDocx = new MimeType(".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    public static readonly MimeType ApplicationDot = new MimeType(".dot", "application/msword");
    public static readonly MimeType ApplicationDotm = new MimeType(".dotm", "application/vnd.ms-word.template.macroEnabled.12");
    public static readonly MimeType ApplicationDotx = new MimeType(".dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template");
    public static readonly MimeType ApplicationDsp = new MimeType(".dsp", "application/octet-stream");
    public static readonly MimeType ApplicationDvi = new MimeType(".dvi", "application/x-dvi");
    public static readonly MimeType ApplicationDwp = new MimeType(".dwp", "application/octet-stream");
    public static readonly MimeType ApplicationDxr = new MimeType(".dxr", "application/x-director");
    public static readonly MimeType ApplicationEmz = new MimeType(".emz", "application/octet-stream");
    public static readonly MimeType ApplicationEot = new MimeType(".eot", "application/vnd.ms-fontobject");
    public static readonly MimeType ApplicationEps = new MimeType(".eps", "application/postscript");
    public static readonly MimeType ApplicationEsd = new MimeType(".esd", "application/vnd.ms-cab-compressed");
    public static readonly MimeType ApplicationEvy = new MimeType(".evy", "application/envoy");
    public static readonly MimeType ApplicationExe = new MimeType(".exe", "application/octet-stream");
    public static readonly MimeType ApplicationFdf = new MimeType(".fdf", "application/vnd.fdf");
    public static readonly MimeType ApplicationFif = new MimeType(".fif", "application/fractals");
    public static readonly MimeType ApplicationFla = new MimeType(".fla", "application/octet-stream");
    public static readonly MimeType ApplicationGtar = new MimeType(".gtar", "application/x-gtar");
    public static readonly MimeType ApplicationGz = new MimeType(".gz", "application/x-gzip");
    public static readonly MimeType ApplicationHdf = new MimeType(".hdf", "application/x-hdf");
    public static readonly MimeType ApplicationHhc = new MimeType(".hhc", "application/x-oleobject");
    public static readonly MimeType ApplicationHhk = new MimeType(".hhk", "application/octet-stream");
    public static readonly MimeType ApplicationHhp = new MimeType(".hhp", "application/octet-stream");
    public static readonly MimeType ApplicationHlp = new MimeType(".hlp", "application/winhlp");
    public static readonly MimeType ApplicationHqx = new MimeType(".hqx", "application/mac-binhex40");
    public static readonly MimeType ApplicationHta = new MimeType(".hta", "application/hta");
    public static readonly MimeType ApplicationIii = new MimeType(".iii", "application/x-iphone");
    public static readonly MimeType ApplicationInf = new MimeType(".inf", "application/octet-stream");
    public static readonly MimeType ApplicationIns = new MimeType(".ins", "application/x-internet-signup");
    public static readonly MimeType ApplicationIsp = new MimeType(".isp", "application/x-internet-signup");
    public static readonly MimeType ApplicationJar = new MimeType(".jar", "application/java-archive");
    public static readonly MimeType ApplicationJava = new MimeType(".java", "application/octet-stream");
    public static readonly MimeType ApplicationJck = new MimeType(".jck", "application/liquidmotion");
    public static readonly MimeType ApplicationJcz = new MimeType(".jcz", "application/liquidmotion");
    public static readonly MimeType ApplicationJpb = new MimeType(".jpb", "application/octet-stream");
    public static readonly MimeType ApplicationJs = new MimeType(".js", "application/javascript");
    public static readonly MimeType ApplicationJson = new MimeType(".json", "application/json");
    public static readonly MimeType ApplicationJsonld = new MimeType(".jsonld", "application/ld+json");
    public static readonly MimeType ApplicationLatex = new MimeType(".latex", "application/x-latex");
    public static readonly MimeType ApplicationLit = new MimeType(".lit", "application/x-ms-reader");
    public static readonly MimeType ApplicationLpk = new MimeType(".lpk", "application/octet-stream");
    public static readonly MimeType ApplicationLzh = new MimeType(".lzh", "application/octet-stream");
    public static readonly MimeType ApplicationM13 = new MimeType(".m13", "application/x-msmediaview");
    public static readonly MimeType ApplicationM14 = new MimeType(".m14", "application/x-msmediaview");
    public static readonly MimeType ApplicationMan = new MimeType(".man", "application/x-troff-man");
    public static readonly MimeType ApplicationManifest = new MimeType(".manifest", "application/x-ms-manifest");
    public static readonly MimeType ApplicationMdb = new MimeType(".mdb", "application/x-msaccess");
    public static readonly MimeType ApplicationMdp = new MimeType(".mdp", "application/octet-stream");
    public static readonly MimeType ApplicationMe = new MimeType(".me", "application/x-troff-me");
    public static readonly MimeType ApplicationMix = new MimeType(".mix", "application/octet-stream");
    public static readonly MimeType ApplicationMmf = new MimeType(".mmf", "application/x-smaf");
    public static readonly MimeType ApplicationMny = new MimeType(".mny", "application/x-msmoney");
    public static readonly MimeType ApplicationMpp = new MimeType(".mpp", "application/vnd.ms-project");
    public static readonly MimeType ApplicationMs = new MimeType(".ms", "application/x-troff-ms");
    public static readonly MimeType ApplicationMsi = new MimeType(".msi", "application/octet-stream");
    public static readonly MimeType ApplicationMso = new MimeType(".mso", "application/octet-stream");
    public static readonly MimeType ApplicationMvb = new MimeType(".mvb", "application/x-msmediaview");
    public static readonly MimeType ApplicationMvc = new MimeType(".mvc", "application/x-miva-compiled");
    public static readonly MimeType ApplicationNc = new MimeType(".nc", "application/x-netcdf");
    public static readonly MimeType ApplicationOcx = new MimeType(".ocx", "application/octet-stream");
    public static readonly MimeType ApplicationOda = new MimeType(".oda", "application/oda");
    public static readonly MimeType ApplicationOds = new MimeType(".ods", "application/oleobject");
    public static readonly MimeType ApplicationOne = new MimeType(".one", "application/onenote");
    public static readonly MimeType ApplicationOnea = new MimeType(".onea", "application/onenote");
    public static readonly MimeType ApplicationOnepkg = new MimeType(".onepkg", "application/onenote");
    public static readonly MimeType ApplicationOnetmp = new MimeType(".onetmp", "application/onenote");
    public static readonly MimeType ApplicationOnetoc = new MimeType(".onetoc", "application/onenote");
    public static readonly MimeType ApplicationOnetoc2 = new MimeType(".onetoc2", "application/onenote");
    public static readonly MimeType ApplicationOsdx = new MimeType(".osdx", "application/opensearchdescription+xml");
    public static readonly MimeType ApplicationP10 = new MimeType(".p10", "application/pkcs10");
    public static readonly MimeType ApplicationP12 = new MimeType(".p12", "application/x-pkcs12");
    public static readonly MimeType ApplicationP7B = new MimeType(".p7b", "application/x-pkcs7-certificates");
    public static readonly MimeType ApplicationP7C = new MimeType(".p7c", "application/pkcs7-mime");
    public static readonly MimeType ApplicationP7M = new MimeType(".p7m", "application/pkcs7-mime");
    public static readonly MimeType ApplicationP7R = new MimeType(".p7r", "application/x-pkcs7-certreqresp");
    public static readonly MimeType ApplicationP7S = new MimeType(".p7s", "application/pkcs7-signature");
    public static readonly MimeType ApplicationPcx = new MimeType(".pcx", "application/octet-stream");
    public static readonly MimeType ApplicationPcz = new MimeType(".pcz", "application/octet-stream");
    public static readonly MimeType ApplicationPdf = new MimeType(".pdf", "application/pdf");
    public static readonly MimeType ApplicationPfb = new MimeType(".pfb", "application/octet-stream");
    public static readonly MimeType ApplicationPfm = new MimeType(".pfm", "application/octet-stream");
    public static readonly MimeType ApplicationPfx = new MimeType(".pfx", "application/x-pkcs12");
    public static readonly MimeType ApplicationPko = new MimeType(".pko", "application/vnd.ms-pki.pko");
    public static readonly MimeType ApplicationPma = new MimeType(".pma", "application/x-perfmon");
    public static readonly MimeType ApplicationPmc = new MimeType(".pmc", "application/x-perfmon");
    public static readonly MimeType ApplicationPml = new MimeType(".pml", "application/x-perfmon");
    public static readonly MimeType ApplicationPmr = new MimeType(".pmr", "application/x-perfmon");
    public static readonly MimeType ApplicationPmw = new MimeType(".pmw", "application/x-perfmon");
    public static readonly MimeType ApplicationPot = new MimeType(".pot", "application/vnd.ms-powerpoint");
    public static readonly MimeType ApplicationPotm = new MimeType(".potm", "application/vnd.ms-powerpoint.template.macroEnabled.12");
    public static readonly MimeType ApplicationPotx = new MimeType(".potx", "application/vnd.openxmlformats-officedocument.presentationml.template");
    public static readonly MimeType ApplicationPpam = new MimeType(".ppam", "application/vnd.ms-powerpoint.addin.macroEnabled.12");
    public static readonly MimeType ApplicationPps = new MimeType(".pps", "application/vnd.ms-powerpoint");
    public static readonly MimeType ApplicationPpsm = new MimeType(".ppsm", "application/vnd.ms-powerpoint.slideshow.macroEnabled.12");
    public static readonly MimeType ApplicationPpsx = new MimeType(".ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow");
    public static readonly MimeType ApplicationPpt = new MimeType(".ppt", "application/vnd.ms-powerpoint");
    public static readonly MimeType ApplicationPptm = new MimeType(".pptm", "application/vnd.ms-powerpoint.presentation.macroEnabled.12");
    public static readonly MimeType ApplicationPptx = new MimeType(".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
    public static readonly MimeType ApplicationPrf = new MimeType(".prf", "application/pics-rules");
    public static readonly MimeType ApplicationPrm = new MimeType(".prm", "application/octet-stream");
    public static readonly MimeType ApplicationPrx = new MimeType(".prx", "application/octet-stream");
    public static readonly MimeType ApplicationPs = new MimeType(".ps", "application/postscript");
    public static readonly MimeType ApplicationPsd = new MimeType(".psd", "application/octet-stream");
    public static readonly MimeType ApplicationPsm = new MimeType(".psm", "application/octet-stream");
    public static readonly MimeType ApplicationPsp = new MimeType(".psp", "application/octet-stream");
    public static readonly MimeType ApplicationPub = new MimeType(".pub", "application/x-mspublisher");
    public static readonly MimeType ApplicationQtl = new MimeType(".qtl", "application/x-quicktimeplayer");
    public static readonly MimeType ApplicationQxd = new MimeType(".qxd", "application/octet-stream");
    public static readonly MimeType ApplicationRar = new MimeType(".rar", "application/octet-stream");
    public static readonly MimeType ApplicationRm = new MimeType(".rm", "application/vnd.rn-realmedia");
    public static readonly MimeType ApplicationRoff = new MimeType(".roff", "application/x-troff");
    public static readonly MimeType ApplicationRtf = new MimeType(".rtf", "application/rtf");
    public static readonly MimeType ApplicationScd = new MimeType(".scd", "application/x-msschedule");
    public static readonly MimeType ApplicationSea = new MimeType(".sea", "application/octet-stream");
    public static readonly MimeType ApplicationSetpay = new MimeType(".setpay", "application/set-payment-initiation");
    public static readonly MimeType ApplicationSetreg = new MimeType(".setreg", "application/set-registration-initiation");
    public static readonly MimeType ApplicationSh = new MimeType(".sh", "application/x-sh");
    public static readonly MimeType ApplicationShar = new MimeType(".shar", "application/x-shar");
    public static readonly MimeType ApplicationSit = new MimeType(".sit", "application/x-stuffit");
    public static readonly MimeType ApplicationSldm = new MimeType(".sldm", "application/vnd.ms-powerpoint.slide.macroEnabled.12");
    public static readonly MimeType ApplicationSldx = new MimeType(".sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide");
    public static readonly MimeType ApplicationSmi = new MimeType(".smi", "application/octet-stream");
    public static readonly MimeType ApplicationSnp = new MimeType(".snp", "application/octet-stream");
    public static readonly MimeType ApplicationSpc = new MimeType(".spc", "application/x-pkcs7-certificates");
    public static readonly MimeType ApplicationSpl = new MimeType(".spl", "application/futuresplash");
    public static readonly MimeType ApplicationSrc = new MimeType(".src", "application/x-wais-source");
    public static readonly MimeType ApplicationSsm = new MimeType(".ssm", "application/streamingmedia");
    public static readonly MimeType ApplicationSst = new MimeType(".sst", "application/vnd.ms-pki.certstore");
    public static readonly MimeType ApplicationStl = new MimeType(".stl", "application/vnd.ms-pki.stl");
    public static readonly MimeType ApplicationSv4Cpio = new MimeType(".sv4cpio", "application/x-sv4cpio");
    public static readonly MimeType ApplicationSv4Crc = new MimeType(".sv4crc", "application/x-sv4crc");
    public static readonly MimeType ApplicationSwf = new MimeType(".swf", "application/x-shockwave-flash");
    public static readonly MimeType ApplicationT = new MimeType(".t", "application/x-troff");
    public static readonly MimeType ApplicationTar = new MimeType(".tar", "application/x-tar");
    public static readonly MimeType ApplicationTcl = new MimeType(".tcl", "application/x-tcl");
    public static readonly MimeType ApplicationTex = new MimeType(".tex", "application/x-tex");
    public static readonly MimeType ApplicationTexi = new MimeType(".texi", "application/x-texinfo");
    public static readonly MimeType ApplicationTexinfo = new MimeType(".texinfo", "application/x-texinfo");
    public static readonly MimeType ApplicationTgz = new MimeType(".tgz", "application/x-compressed");
    public static readonly MimeType ApplicationThmx = new MimeType(".thmx", "application/vnd.ms-officetheme");
    public static readonly MimeType ApplicationThn = new MimeType(".thn", "application/octet-stream");
    public static readonly MimeType ApplicationToc = new MimeType(".toc", "application/octet-stream");
    public static readonly MimeType ApplicationTr = new MimeType(".tr", "application/x-troff");
    public static readonly MimeType ApplicationTrm = new MimeType(".trm", "application/x-msterminal");
    public static readonly MimeType ApplicationTtf = new MimeType(".ttf", "application/octet-stream");
    public static readonly MimeType ApplicationU32 = new MimeType(".u32", "application/octet-stream");
    public static readonly MimeType ApplicationUstar = new MimeType(".ustar", "application/x-ustar");
    public static readonly MimeType ApplicationVdx = new MimeType(".vdx", "application/vnd.ms-visio.viewer");
    public static readonly MimeType ApplicationVsd = new MimeType(".vsd", "application/vnd.visio");
    public static readonly MimeType ApplicationVss = new MimeType(".vss", "application/vnd.visio");
    public static readonly MimeType ApplicationVst = new MimeType(".vst", "application/vnd.visio");
    public static readonly MimeType ApplicationVsto = new MimeType(".vsto", "application/x-ms-vsto");
    public static readonly MimeType ApplicationVsw = new MimeType(".vsw", "application/vnd.visio");
    public static readonly MimeType ApplicationVsx = new MimeType(".vsx", "application/vnd.visio");
    public static readonly MimeType ApplicationVtx = new MimeType(".vtx", "application/vnd.visio");
    public static readonly MimeType ApplicationWasm = new MimeType(".wasm", "application/wasm");
    public static readonly MimeType ApplicationWcm = new MimeType(".wcm", "application/vnd.ms-works");
    public static readonly MimeType ApplicationWdb = new MimeType(".wdb", "application/vnd.ms-works");
    public static readonly MimeType ApplicationWks = new MimeType(".wks", "application/vnd.ms-works");
    public static readonly MimeType ApplicationWmd = new MimeType(".wmd", "application/x-ms-wmd");
    public static readonly MimeType ApplicationWmf = new MimeType(".wmf", "application/x-msmetafile");
    public static readonly MimeType ApplicationWmlc = new MimeType(".wmlc", "application/vnd.wap.wmlc");
    public static readonly MimeType ApplicationWmlsc = new MimeType(".wmlsc", "application/vnd.wap.wmlscriptc");
    public static readonly MimeType ApplicationWmz = new MimeType(".wmz", "application/x-ms-wmz");
    public static readonly MimeType ApplicationWoff2 = new MimeType(".woff2", "application/font-woff2");
    public static readonly MimeType ApplicationWps = new MimeType(".wps", "application/vnd.ms-works");
    public static readonly MimeType ApplicationWri = new MimeType(".wri", "application/x-mswrite");
    public static readonly MimeType ApplicationX = new MimeType(".x", "application/directx");
    public static readonly MimeType ApplicationXaml = new MimeType(".xaml", "application/xaml+xml");
    public static readonly MimeType ApplicationXap = new MimeType(".xap", "application/x-silverlight-app");
    public static readonly MimeType ApplicationXbap = new MimeType(".xbap", "application/x-ms-xbap");
    public static readonly MimeType ApplicationXht = new MimeType(".xht", "application/xhtml+xml");
    public static readonly MimeType ApplicationXhtml = new MimeType(".xhtml", "application/xhtml+xml");
    public static readonly MimeType ApplicationXla = new MimeType(".xla", "application/vnd.ms-excel");
    public static readonly MimeType ApplicationXlam = new MimeType(".xlam", "application/vnd.ms-excel.addin.macroEnabled.12");
    public static readonly MimeType ApplicationXlc = new MimeType(".xlc", "application/vnd.ms-excel");
    public static readonly MimeType ApplicationXlm = new MimeType(".xlm", "application/vnd.ms-excel");
    public static readonly MimeType ApplicationXls = new MimeType(".xls", "application/vnd.ms-excel");
    public static readonly MimeType ApplicationXlsb = new MimeType(".xlsb", "application/vnd.ms-excel.sheet.binary.macroEnabled.12");
    public static readonly MimeType ApplicationXlsm = new MimeType(".xlsm", "application/vnd.ms-excel.sheet.macroEnabled.12");
    public static readonly MimeType ApplicationXlsx = new MimeType(".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    public static readonly MimeType ApplicationXlt = new MimeType(".xlt", "application/vnd.ms-excel");
    public static readonly MimeType ApplicationXltm = new MimeType(".xltm", "application/vnd.ms-excel.template.macroEnabled.12");
    public static readonly MimeType ApplicationXltx = new MimeType(".xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template");
    public static readonly MimeType ApplicationXlw = new MimeType(".xlw", "application/vnd.ms-excel");
    public static readonly MimeType ApplicationXps = new MimeType(".xps", "application/vnd.ms-xpsdocument");
    public static readonly MimeType ApplicationXsn = new MimeType(".xsn", "application/octet-stream");
    public static readonly MimeType ApplicationXtp = new MimeType(".xtp", "application/octet-stream");
    public static readonly MimeType ApplicationZ = new MimeType(".z", "application/x-compress");
    public static readonly MimeType ApplicationZip = new MimeType(".zip", "application/x-zip-compressed");
    public static readonly MimeType AudioAac = new MimeType(".aac", "audio/aac");
    public static readonly MimeType AudioAdt = new MimeType(".adt", "audio/vnd.dlna.adts");
    public static readonly MimeType AudioAdts = new MimeType(".adts", "audio/vnd.dlna.adts");
    public static readonly MimeType AudioAif = new MimeType(".aif", "audio/x-aiff");
    public static readonly MimeType AudioAifc = new MimeType(".aifc", "audio/aiff");
    public static readonly MimeType AudioAiff = new MimeType(".aiff", "audio/aiff");
    public static readonly MimeType AudioAu = new MimeType(".au", "audio/basic");
    public static readonly MimeType AudioM3U = new MimeType(".m3u", "audio/x-mpegurl");
    public static readonly MimeType AudioM4A = new MimeType(".m4a", "audio/mp4");
    public static readonly MimeType AudioMid = new MimeType(".mid", "audio/mid");
    public static readonly MimeType AudioMidi = new MimeType(".midi", "audio/mid");
    public static readonly MimeType AudioMp3 = new MimeType(".mp3", "audio/mpeg");
    public static readonly MimeType AudioOga = new MimeType(".oga", "audio/ogg");
    public static readonly MimeType AudioRa = new MimeType(".ra", "audio/x-pn-realaudio");
    public static readonly MimeType AudioRam = new MimeType(".ram", "audio/x-pn-realaudio");
    public static readonly MimeType AudioRmi = new MimeType(".rmi", "audio/mid");
    public static readonly MimeType AudioRpm = new MimeType(".rpm", "audio/x-pn-realaudio-plugin");
    public static readonly MimeType AudioSmd = new MimeType(".smd", "audio/x-smd");
    public static readonly MimeType AudioSmx = new MimeType(".smx", "audio/x-smd");
    public static readonly MimeType AudioSmz = new MimeType(".smz", "audio/x-smd");
    public static readonly MimeType AudioSnd = new MimeType(".snd", "audio/basic");
    public static readonly MimeType AudioSpx = new MimeType(".spx", "audio/ogg");
    public static readonly MimeType AudioWav = new MimeType(".wav", "audio/wav");
    public static readonly MimeType AudioWax = new MimeType(".wax", "audio/x-ms-wax");
    public static readonly MimeType AudioWma = new MimeType(".wma", "audio/x-ms-wma");
    public static readonly MimeType DrawingDwf = new MimeType(".dwf", "drawing/x-dwf");
    public static readonly MimeType FontOtf = new MimeType(".otf", "font/otf");
    public static readonly MimeType FontWoff = new MimeType(".woff", "font/x-woff");
    public static readonly MimeType ImageArt = new MimeType(".art", "image/x-jg");
    public static readonly MimeType ImageBmp = new MimeType(".bmp", "image/bmp");
    public static readonly MimeType ImageCmx = new MimeType(".cmx", "image/x-cmx");
    public static readonly MimeType ImageCod = new MimeType(".cod", "image/cis-cod");
    public static readonly MimeType ImageDib = new MimeType(".dib", "image/bmp");
    public static readonly MimeType ImageGif = new MimeType(".gif", "image/gif");
    public static readonly MimeType ImageIco = new MimeType(".ico", "image/x-icon");
    public static readonly MimeType ImageIef = new MimeType(".ief", "image/ief");
    public static readonly MimeType ImageJfif = new MimeType(".jfif", "image/pjpeg");
    public static readonly MimeType ImageJpe = new MimeType(".jpe", "image/jpeg");
    public static readonly MimeType ImageJpeg = new MimeType(".jpeg", "image/jpeg");
    public static readonly MimeType ImageJpg = new MimeType(".jpg", "image/jpeg");
    public static readonly MimeType ImagePbm = new MimeType(".pbm", "image/x-portable-bitmap");
    public static readonly MimeType ImagePgm = new MimeType(".pgm", "image/x-portable-graymap");
    public static readonly MimeType ImagePng = new MimeType(".png", "image/png");
    public static readonly MimeType ImagePnm = new MimeType(".pnm", "image/x-portable-anymap");
    public static readonly MimeType ImagePnz = new MimeType(".pnz", "image/png");
    public static readonly MimeType ImagePpm = new MimeType(".ppm", "image/x-portable-pixmap");
    public static readonly MimeType ImageRas = new MimeType(".ras", "image/x-cmu-raster");
    public static readonly MimeType ImageRf = new MimeType(".rf", "image/vnd.rn-realflash");
    public static readonly MimeType ImageRgb = new MimeType(".rgb", "image/x-rgb");
    public static readonly MimeType ImageSvg = new MimeType(".svg", "image/svg+xml");
    public static readonly MimeType ImageSvgz = new MimeType(".svgz", "image/svg+xml");
    public static readonly MimeType ImageTif = new MimeType(".tif", "image/tiff");
    public static readonly MimeType ImageTiff = new MimeType(".tiff", "image/tiff");
    public static readonly MimeType ImageWbmp = new MimeType(".wbmp", "image/vnd.wap.wbmp");
    public static readonly MimeType ImageXbm = new MimeType(".xbm", "image/x-xbitmap");
    public static readonly MimeType ImageXpm = new MimeType(".xpm", "image/x-xpixmap");
    public static readonly MimeType ImageXwd = new MimeType(".xwd", "image/x-xwindowdump");
    public static readonly MimeType MessageEml = new MimeType(".eml", "message/rfc822");
    public static readonly MimeType MessageMht = new MimeType(".mht", "message/rfc822");
    public static readonly MimeType MessageMhtml = new MimeType(".mhtml", "message/rfc822");
    public static readonly MimeType MessageNws = new MimeType(".nws", "message/rfc822");
    public static readonly MimeType ModelGlb = new MimeType(".glb", "model/gltf-binary");
    public static readonly MimeType Text323 = new MimeType(".323", "text/h323");
    public static readonly MimeType TextAppcache = new MimeType(".appcache", "text/cache-manifest");
    public static readonly MimeType TextAsm = new MimeType(".asm", "text/plain");
    public static readonly MimeType TextBas = new MimeType(".bas", "text/plain");
    public static readonly MimeType TextC = new MimeType(".c", "text/plain");
    public static readonly MimeType TextCnf = new MimeType(".cnf", "text/plain");
    public static readonly MimeType TextCpp = new MimeType(".cpp", "text/plain");
    public static readonly MimeType TextCss = new MimeType(".css", "text/css");
    public static readonly MimeType TextDisco = new MimeType(".disco", "text/xml");
    public static readonly MimeType TextDllConfig = new MimeType(".dll.config", "text/xml");
    public static readonly MimeType TextDlm = new MimeType(".dlm", "text/dlm");
    public static readonly MimeType TextDtd = new MimeType(".dtd", "text/xml");
    public static readonly MimeType TextEtx = new MimeType(".etx", "text/x-setext");
    public static readonly MimeType TextExeConfig = new MimeType(".exe.config", "text/xml");
    public static readonly MimeType TextH = new MimeType(".h", "text/plain");
    public static readonly MimeType TextHdml = new MimeType(".hdml", "text/x-hdml");
    public static readonly MimeType TextHtc = new MimeType(".htc", "text/x-component");
    public static readonly MimeType TextHtm = new MimeType(".htm", "text/html");
    public static readonly MimeType TextHtml = new MimeType(".html", "text/html");
    public static readonly MimeType TextHtt = new MimeType(".htt", "text/webviewhtml");
    public static readonly MimeType TextHxt = new MimeType(".hxt", "text/html");
    public static readonly MimeType TextIcs = new MimeType(".ics", "text/calendar");
    public static readonly MimeType TextJsx = new MimeType(".jsx", "text/jscript");
    public static readonly MimeType TextLess = new MimeType(".less", "text/css");
    public static readonly MimeType TextMap = new MimeType(".map", "text/plain");
    public static readonly MimeType TextMno = new MimeType(".mno", "text/xml");
    public static readonly MimeType TextOdc = new MimeType(".odc", "text/x-ms-odc");
    public static readonly MimeType TextRtx = new MimeType(".rtx", "text/richtext");
    public static readonly MimeType TextSct = new MimeType(".sct", "text/scriptlet");
    public static readonly MimeType TextSgml = new MimeType(".sgml", "text/sgml");
    public static readonly MimeType TextTsv = new MimeType(".tsv", "text/tab-separated-values");
    public static readonly MimeType TextTxt = new MimeType(".txt", "text/plain");
    public static readonly MimeType TextUls = new MimeType(".uls", "text/iuls");
    public static readonly MimeType TextVbs = new MimeType(".vbs", "text/vbscript");
    public static readonly MimeType TextVcf = new MimeType(".vcf", "text/x-vcard");
    public static readonly MimeType TextVcs = new MimeType(".vcs", "text/plain");
    public static readonly MimeType TextVml = new MimeType(".vml", "text/xml");
    public static readonly MimeType TextWml = new MimeType(".wml", "text/vnd.wap.wml");
    public static readonly MimeType TextWmls = new MimeType(".wmls", "text/vnd.wap.wmlscript");
    public static readonly MimeType TextWsdl = new MimeType(".wsdl", "text/xml");
    public static readonly MimeType TextXdr = new MimeType(".xdr", "text/plain");
    public static readonly MimeType TextXml = new MimeType(".xml", "text/xml");
    public static readonly MimeType TextXsd = new MimeType(".xsd", "text/xml");
    public static readonly MimeType TextXsf = new MimeType(".xsf", "text/xml");
    public static readonly MimeType TextXsl = new MimeType(".xsl", "text/xml");
    public static readonly MimeType TextXslt = new MimeType(".xslt", "text/xml");
    public static readonly MimeType Video3G2 = new MimeType(".3g2", "video/3gpp2");
    public static readonly MimeType Video3Gp = new MimeType(".3gp", "video/3gpp");
    public static readonly MimeType Video3Gp2 = new MimeType(".3gp2", "video/3gpp2");
    public static readonly MimeType Video3Gpp = new MimeType(".3gpp", "video/3gpp");
    public static readonly MimeType VideoAsf = new MimeType(".asf", "video/x-ms-asf");
    public static readonly MimeType VideoAsr = new MimeType(".asr", "video/x-ms-asf");
    public static readonly MimeType VideoAsx = new MimeType(".asx", "video/x-ms-asf");
    public static readonly MimeType VideoAvi = new MimeType(".avi", "video/avi");
    public static readonly MimeType VideoDvrMs = new MimeType(".dvr-ms", "video/x-ms-dvr");
    public static readonly MimeType VideoFlv = new MimeType(".flv", "video/x-flv");
    public static readonly MimeType VideoIvf = new MimeType(".ivf", "video/x-ivf");
    public static readonly MimeType VideoLsf = new MimeType(".lsf", "video/x-la-asf");
    public static readonly MimeType VideoLsx = new MimeType(".lsx", "video/x-la-asf");
    public static readonly MimeType VideoM1V = new MimeType(".m1v", "video/mpeg");
    public static readonly MimeType VideoM2Ts = new MimeType(".m2ts", "video/vnd.dlna.mpeg-tts");
    public static readonly MimeType VideoM4V = new MimeType(".m4v", "video/mp4");
    public static readonly MimeType VideoMov = new MimeType(".mov", "video/quicktime");
    public static readonly MimeType VideoMovie = new MimeType(".movie", "video/x-sgi-movie");
    public static readonly MimeType VideoMp2 = new MimeType(".mp2", "video/mpeg");
    public static readonly MimeType VideoMp4 = new MimeType(".mp4", "video/mp4");
    public static readonly MimeType VideoMp4V = new MimeType(".mp4v", "video/mp4");
    public static readonly MimeType VideoMpa = new MimeType(".mpa", "video/mpeg");
    public static readonly MimeType VideoMpe = new MimeType(".mpe", "video/mpeg");
    public static readonly MimeType VideoMpeg = new MimeType(".mpeg", "video/mpeg");
    public static readonly MimeType VideoMpg = new MimeType(".mpg", "video/mpeg");
    public static readonly MimeType VideoMpv2 = new MimeType(".mpv2", "video/mpeg");
    public static readonly MimeType VideoNsc = new MimeType(".nsc", "video/x-ms-asf");
    public static readonly MimeType VideoOgg = new MimeType(".ogg", "video/ogg");
    public static readonly MimeType VideoOgv = new MimeType(".ogv", "video/ogg");
    public static readonly MimeType VideoQt = new MimeType(".qt", "video/quicktime");
    public static readonly MimeType VideoTs = new MimeType(".ts", "video/vnd.dlna.mpeg-tts");
    public static readonly MimeType VideoTts = new MimeType(".tts", "video/vnd.dlna.mpeg-tts");
    public static readonly MimeType VideoWebm = new MimeType(".webm", "video/webm");
    public static readonly MimeType VideoWm = new MimeType(".wm", "video/x-ms-wm");
    public static readonly MimeType VideoWmp = new MimeType(".wmp", "video/x-ms-wmp");
    public static readonly MimeType VideoWmv = new MimeType(".wmv", "video/x-ms-wmv");
    public static readonly MimeType VideoWmx = new MimeType(".wmx", "video/x-ms-wmx");
    public static readonly MimeType VideoWtv = new MimeType(".wtv", "video/x-ms-wtv");
    public static readonly MimeType VideoWvx = new MimeType(".wvx", "video/x-ms-wvx");
    public static readonly MimeType XWorldFlr = new MimeType(".flr", "x-world/x-vrml");
    public static readonly MimeType XWorldWrl = new MimeType(".wrl", "x-world/x-vrml");
    public static readonly MimeType XWorldWrz = new MimeType(".wrz", "x-world/x-vrml");
    public static readonly MimeType XWorldXaf = new MimeType(".xaf", "x-world/x-vrml");
    public static readonly MimeType XWorldXof = new MimeType(".xof", "x-world/x-vrml");
}